GREEN_LIZARD = {
    'waving hand': "CAACAgIAAxkBAAPqZYWOuHaVNf_6wcc_ZxxXytqpNfgAArgAA_cCyA9GC5y04k4LODME",
    'no idea': "CAACAgIAAxkBAAPtZYWOz3Mb8CbrdR_m4Uak30wwqFwAAs4AA_cCyA9cmEfgzKtuijME",
    'pissed off': "CAACAgIAAxkBAAPwZYWO9YfNTqdawAkrwCYFS2hacvQAArkAA_cCyA-QIar4OXdG2DME",
    'ok': "CAACAgIAAxkBAAPzZYWRIjQ1OFnkqon0FM5FRmJFvjMAAroAA_cCyA_9DDg86phXuTME",
    'deep thinking': "CAACAgIAAxkBAAP2ZYWRNXPOAAEcYShdKCk_r4WzfwV-AAK3AAP3AsgPkPG2BzshSB0zBA",
    'easy': "CAACAgIAAxkBAAP5ZYWRR-H-TqKgJ9WhQn9HfZQMrAMAAsMAA_cCyA-ScOAAAWuXY2UzBA"
}

BLACK_CHERRY = {
    'waving hand': "CAACAgIAAxkBAAIBBGWFkuS2phyHYmHo3xOErTUDqVZ8AAINBwACnebQSDlE3V0e4u2NMwQ",
    'making fun': "CAACAgIAAxkBAAIBEGWFk5dgxYZdBUi2fSthTuFMRp9MAAIQCQACLOLgSbwlufsIzsBaMwQ",
    'not funny': "CAACAgIAAxkBAAIBFmWFlLQbYJcFNhqBAruPpz8Cj8E-AALABwACDY7QSA-Th02yUO4GMwQ",
    'blinking': "CAACAgIAAxkBAAIBGWWFlSNONPa6y_5hyGnPP_gC5VJ-AAIdBwACDzAISqfDjFg_h9ZAMwQ",
    'mission accomplished': "CAACAgIAAxkBAAIBHGWFlYAgfy8rCitIvIpDa_1D3sXCAALZHQAC7tGYSWdeZ2Je_P0xMwQ",
    'panic': "CAACAgIAAxkBAAIBH2WFlte1TX-wj95kN6g3vlHZWWSGAAL_BwAChb3ZSM1p-ygbadUVMwQ",
    'disappointed': "CAACAgIAAxkBAAIBMmWFmV6k7x0a-_8l02mPnQwLCp2PAAIgCQACptnQSEs16t0wYwKwMwQ",
    'bite me': "CAACAgIAAxkBAAIBcGWFp7dibycTeXEIxNMJVRgV8sTlAAL8CAACTFPRSBs7RareVHjTMwQ",
    'oops': "CAACAgIAAxkBAAIJKWYoAVmc4WIqpJJ22OsS8CYIZjeVAAIzCAACBSvYSoIQ2sHgbvIsNAQ"
}